#!/usr/bin/env bash

_kill_procs() {
  kill -TERM $bbc_a11y
  wait $bbc_a11y
  kill -TERM $xvfb
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

XVFB_WHD=${XVFB_WHD:-1280x720x16}

# Start Xvfb
Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp &
xvfb=$!

export DISPLAY=:99

node /usr/local/lib/node_modules/bbc-a11y/bin/bbc-a11y.js $@ &
bbc_a11y=$!

wait $bbc_a11y
